# Continuous Integration build configuration
# cribbed from travis-ci/travis-ci-rust-example
# https://github.com/travis-ci/travis-ci-rust-example/blob/master/.travis.yml
language: rust

# We rely on libsqlite3-dev, which seems to be part of the default
# travis-ci build environment.
