language: rust
sudo: false
addons:
  apt:
    packages:
      - sqlite3
      - libsqlite3-dev

rust:
  - nightly
  - beta
  - stable

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc -- --no-deps
after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "hMalmHYxRhzP/zLuKHfi9Zhz7mPeCugGJznazgyYeNBNZiWWoZSVBSTE7I0MFXVymsb72wK8Z3FXGa2cu9zozSbX3f938516t9lBtQakUUfLTG3uHVvn971UEeXRRN2hvaI9rMzy1GqbcHZ+zgtMJ0FdiTQiwklem/xS8qpgkY5ovcAg93q3POdnRdqL2kwQlUPQFUZ7WxAiotVmU/ejwWz4GN3kzl3umyHlxZTxgG3gOmu6BM+GdyghmBqettQLEF4mfsOpj9fCH1pH/9lox5IHHT1MutM0hNbD4A85FKFID6g6UCpvQA/7SY/vFVr94ah6osCo8t3GbXxJ0eBlnecluLWIWmtmBKxEh+N9Q3FsDzF11g5mxF5YrowuJlwp0RE215Jt6oDKx3xuUhOx0kW2gq7gIQ4dFxikroZfA/iHR660Mvq9IL7gGFyrKAPngx8joXh1h5l1MOr7T1xv9qaInNdgPVKlM9tt3F5Bb+gFk1RiNCTyhVmDKLLFQh6lHLyFN5/WPf26x8+rZq/IRCjbFqesMNQQqbPcAJ89VjL9TPohBl9Aw3321c6RiJOxNFtz+4Fcw0i48m23M7aYEqz+xfSlPvtRcTjFObXMRUiaoB6zQj78yNjWsN2ZfgBua3EqZ5sLkjEIjd7NLSZzYCg3k5oRcXOSXGb2r2vLRps="
