# Continuous Integration build configuration
#
# cribbed from sfackler
#  - https://github.com/sfackler/rust-postgres/blob/master/.travis.yml
#
# See also:
#  - http://www.rust-ci.org/p/390/artifactconf

language: rust
env:
  global:
    - secure: Ec6ZjLg8P0hLYZf2rBzTcGKidavRNzBSuYr1dxuB4OD/X5z9LToSBNomAnxIeBEU7kQKlnYTJUW34bcd6IVt0PlYm/JT3Ij4RBIUwHjWTnyH2GObmtUfDsoxeaSROCWsoogWNG1tGYp23iTHaVqcKMOWLpcZtmzYYnlTCPNSHmo=
script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_script:
  - mv target/doc .
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh


# We rely on libsqlite3-dev, which seems to be part of the default
# travis-ci build environment.

# In travis-ci-rust-example, it just has:
#   language: rust
# but this doesn't seem to suffice for building docs.
#  - https://github.com/travis-ci/travis-ci-rust-example/blob/master/.travis.yml

